# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='basic_site.Teacher'),
        ),
    ]
